package com.data.account.factory;

import com.data.account.dao.IDataInfoDao;
import com.data.account.dao.impl.DataInfoDaoImpl;


/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class DataInfoFactory implements IDaoFactory
{
    private static IDataInfoDao dao;

    public static IDataInfoDao getDao()
    {
		if (dao == null)
			dao = new DataInfoDaoImpl(mainHelper);

        return dao;
    }
}