package com.data.account.factory;

import com.data.account.dao.ITableDataDao;
import com.data.account.dao.impl.TableDataDaoImpl;


/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class TableDataFactory implements IDaoFactory
{
    private static ITableDataDao dao;

    public static ITableDataDao getDao()
    {
		if (dao == null)
			dao = new TableDataDaoImpl(mainHelper);

        return dao;
    }
}