package com.data.log.dao;

import com.base.database.IBaseDao;
import java.util.List;

import com.data.log.ItemOperateLog;


/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public interface IItemOperateLogDao extends IBaseDao<ItemOperateLog>
{
	List<ItemOperateLog> getItemOperateLogByUserID(long userID);

}
