package com.data.log.dao;

import com.base.database.IBaseDao;
import java.util.List;

import com.data.log.ResourceLog;


/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public interface IResourceLogDao extends IBaseDao<ResourceLog>
{
	List<ResourceLog> getResourceLogByUserID(int userID);

}
