package com.data.account.data;


import com.base.data.ChangedObject;

/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class TableData extends ChangedObject 
{
	/**
	 * 
	 */
	private int tableID;

	/**
	 * 
	 */
	private long value;

	/**
	 * 
	 */
	private String tableDesc;


    public TableData()
    {
       super();
    }

	/**
	 * 
	 */
	public int getTableID()
	{
		return tableID;
	}

	/**
	 * 
	 */
	public void setTableID(int tableID)
	{
		if(tableID != this.tableID)
		{
			this.tableID = tableID;
			setChanged(true);
		}
	}

	/**
	 * 
	 */
	public long getValue()
	{
		return value;
	}

	/**
	 * 
	 */
	public void setValue(long value)
	{
		if(value != this.value)
		{
			this.value = value;
			setChanged(true);
		}
	}

	/**
	 * 
	 */
	public String getTableDesc()
	{
		return tableDesc;
	}

	/**
	 * 
	 */
	public void setTableDesc(String tableDesc)
	{
		if(tableDesc != null)
		{
			if(!tableDesc.equals(this.tableDesc))
			{
				this.tableDesc = tableDesc;
				setChanged(true);
			}
		}
		else
		{
			if(tableDesc != this.tableDesc)
			{
				this.tableDesc = tableDesc;
				setChanged(true);
			}
		}
	}


	/**
	 * x.clone() != x
	 */
	public TableData clone()
	{
		TableData clone = new TableData();
		clone.setTableID(this.getTableID());
		clone.setValue(this.getValue());
		clone.setTableDesc(this.getTableDesc());
		return clone;
	}

	/**
	 * 重置信息
	 */
	public void reset(TableData info)
	{
		this.setTableID(info.getTableID());
		this.setValue(info.getValue());
		this.setTableDesc(info.getTableDesc());
	}

}