package com.data.account.data;

import java.util.Date;

import com.base.data.ChangedObject;

/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class UserData extends ChangedObject 
{
	/**
	 * 玩家ID
	 */
	private long userID;

	/**
	 * OpenID
	 */
	private String openID;

	/**
	 * 玩家名
	 */
	private String userName;

	/**
	 * 密码
	 */
	private String password;

	/**
	 * 注册日期
	 */
	private Date registerDate;

	/**
	 * 上次登录日期
	 */
	private Date lastLoginDate;

	/**
	 * 财富
	 */
	private int gold;

	/**
	 * 等级
	 */
	private int level;

	/**
	 * 货币
	 */
	private int money;


    public UserData()
    {
       super();
    }

	/**
	 * 玩家ID
	 */
	public long getUserID()
	{
		return userID;
	}

	/**
	 * 玩家ID
	 */
	public void setUserID(long userID)
	{
		if(userID != this.userID)
		{
			this.userID = userID;
			setChanged(true);
		}
	}

	/**
	 * OpenID
	 */
	public String getOpenID()
	{
		return openID;
	}

	/**
	 * OpenID
	 */
	public void setOpenID(String openID)
	{
		if(openID != null)
		{
			if(!openID.equals(this.openID))
			{
				this.openID = openID;
				setChanged(true);
			}
		}
		else
		{
			if(openID != this.openID)
			{
				this.openID = openID;
				setChanged(true);
			}
		}
	}

	/**
	 * 玩家名
	 */
	public String getUserName()
	{
		return userName;
	}

	/**
	 * 玩家名
	 */
	public void setUserName(String userName)
	{
		if(userName != null)
		{
			if(!userName.equals(this.userName))
			{
				this.userName = userName;
				setChanged(true);
			}
		}
		else
		{
			if(userName != this.userName)
			{
				this.userName = userName;
				setChanged(true);
			}
		}
	}

	/**
	 * 密码
	 */
	public String getPassword()
	{
		return password;
	}

	/**
	 * 密码
	 */
	public void setPassword(String password)
	{
		if(password != null)
		{
			if(!password.equals(this.password))
			{
				this.password = password;
				setChanged(true);
			}
		}
		else
		{
			if(password != this.password)
			{
				this.password = password;
				setChanged(true);
			}
		}
	}

	/**
	 * 注册日期
	 */
	public Date getRegisterDate()
	{
		return registerDate;
	}

	/**
	 * 注册日期
	 */
	public void setRegisterDate(Date registerDate)
	{
		if(registerDate != null)
		{
			if(!registerDate.equals(this.registerDate))
			{
				this.registerDate = registerDate;
				setChanged(true);
			}
		}
		else
		{
			if(registerDate != this.registerDate)
			{
				this.registerDate = registerDate;
				setChanged(true);
			}
		}
	}

	/**
	 * 上次登录日期
	 */
	public Date getLastLoginDate()
	{
		return lastLoginDate;
	}

	/**
	 * 上次登录日期
	 */
	public void setLastLoginDate(Date lastLoginDate)
	{
		if(lastLoginDate != null)
		{
			if(!lastLoginDate.equals(this.lastLoginDate))
			{
				this.lastLoginDate = lastLoginDate;
				setChanged(true);
			}
		}
		else
		{
			if(lastLoginDate != this.lastLoginDate)
			{
				this.lastLoginDate = lastLoginDate;
				setChanged(true);
			}
		}
	}

	/**
	 * 财富
	 */
	public int getGold()
	{
		return gold;
	}

	/**
	 * 财富
	 */
	public void setGold(int gold)
	{
		if(gold != this.gold)
		{
			this.gold = gold;
			setChanged(true);
		}
	}

	/**
	 * 等级
	 */
	public int getLevel()
	{
		return level;
	}

	/**
	 * 等级
	 */
	public void setLevel(int level)
	{
		if(level != this.level)
		{
			this.level = level;
			setChanged(true);
		}
	}

	/**
	 * 货币
	 */
	public int getMoney()
	{
		return money;
	}

	/**
	 * 货币
	 */
	public void setMoney(int money)
	{
		if(money != this.money)
		{
			this.money = money;
			setChanged(true);
		}
	}


	/**
	 * x.clone() != x
	 */
	public UserData clone()
	{
		UserData clone = new UserData();
		clone.setUserID(this.getUserID());
		clone.setOpenID(this.getOpenID());
		clone.setUserName(this.getUserName());
		clone.setPassword(this.getPassword());
		clone.setRegisterDate(this.getRegisterDate());
		clone.setLastLoginDate(this.getLastLoginDate());
		clone.setGold(this.getGold());
		clone.setLevel(this.getLevel());
		clone.setMoney(this.getMoney());
		return clone;
	}

	/**
	 * 重置信息
	 */
	public void reset(UserData info)
	{
		this.setUserID(info.getUserID());
		this.setOpenID(info.getOpenID());
		this.setUserName(info.getUserName());
		this.setPassword(info.getPassword());
		this.setRegisterDate(info.getRegisterDate());
		this.setLastLoginDate(info.getLastLoginDate());
		this.setGold(info.getGold());
		this.setLevel(info.getLevel());
		this.setMoney(info.getMoney());
	}

}