package com.data.log.factory;

import com.data.log.dao.IResourceLogDao;
import com.data.log.dao.impl.ResourceLogDaoImpl;

import com.data.factory.IDaoFactory;


/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class ResourceLogFactory implements IDaoFactory
{
    private static IResourceLogDao dao;

    public static IResourceLogDao getDao()
    {
		if (dao == null)
			dao = new ResourceLogDaoImpl(logHelper);

        return dao;
    }
}