package com.upload.data.dao;

import com.upload.data.data.ServerData;
import com.upload.database.IBaseDao;

/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public interface IServerDataDao extends IBaseDao<ServerData>
{
}
