package com.data.account.dao;

import com.base.database.IBaseDao;
import java.util.List;

import com.data.account.data.CommonData;


/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public interface ICommonDataDao extends IBaseDao<CommonData>
{
}
