package com.data.account.info;


import com.base.data.ChangedObject;

/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class DataInfo extends ChangedObject 
{
	/**
	 * 主键
	 */
	private long keyID;

	/**
	 * 玩家ID
	 */
	private long userID;

	/**
	 * 分组
	 */
	private String groupID;

	/**
	 * 数据
	 */
	private String content;


    public DataInfo()
    {
       super();
    }

	/**
	 * 主键
	 */
	public long getKeyID()
	{
		return keyID;
	}

	/**
	 * 主键
	 */
	public void setKeyID(long keyID)
	{
		if(keyID != this.keyID)
		{
			this.keyID = keyID;
			setChanged(true);
		}
	}

	/**
	 * 玩家ID
	 */
	public long getUserID()
	{
		return userID;
	}

	/**
	 * 玩家ID
	 */
	public void setUserID(long userID)
	{
		if(userID != this.userID)
		{
			this.userID = userID;
			setChanged(true);
		}
	}

	/**
	 * 分组
	 */
	public String getGroupID()
	{
		return groupID;
	}

	/**
	 * 分组
	 */
	public void setGroupID(String groupID)
	{
		if(groupID != null)
		{
			if(!groupID.equals(this.groupID))
			{
				this.groupID = groupID;
				setChanged(true);
			}
		}
		else
		{
			if(groupID != this.groupID)
			{
				this.groupID = groupID;
				setChanged(true);
			}
		}
	}

	/**
	 * 数据
	 */
	public String getContent()
	{
		return content;
	}

	/**
	 * 数据
	 */
	public void setContent(String content)
	{
		if(content != null)
		{
			if(!content.equals(this.content))
			{
				this.content = content;
				setChanged(true);
			}
		}
		else
		{
			if(content != this.content)
			{
				this.content = content;
				setChanged(true);
			}
		}
	}


	/**
	 * x.clone() != x
	 */
	public DataInfo clone()
	{
		DataInfo clone = new DataInfo();
		clone.setKeyID(this.getKeyID());
		clone.setUserID(this.getUserID());
		clone.setGroupID(this.getGroupID());
		clone.setContent(this.getContent());
		return clone;
	}

	/**
	 * 重置信息
	 */
	public void reset(DataInfo info)
	{
		this.setKeyID(info.getKeyID());
		this.setUserID(info.getUserID());
		this.setGroupID(info.getGroupID());
		this.setContent(info.getContent());
	}

}