package com.data.account.data;


import com.base.data.ChangedObject;

/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class CommonData extends ChangedObject 
{
	/**
	 * 公告类型
	 */
	private int noticeType;

	/**
	 * 语言类型
	 */
	private String languageType;

	/**
	 * 公告
	 */
	private String noticeMessage;


    public CommonData()
    {
       super();
    }

	/**
	 * 公告类型
	 */
	public int getNoticeType()
	{
		return noticeType;
	}

	/**
	 * 公告类型
	 */
	public void setNoticeType(int noticeType)
	{
		if(noticeType != this.noticeType)
		{
			this.noticeType = noticeType;
			setChanged(true);
		}
	}

	/**
	 * 语言类型
	 */
	public String getLanguageType()
	{
		return languageType;
	}

	/**
	 * 语言类型
	 */
	public void setLanguageType(String languageType)
	{
		if(languageType != null)
		{
			if(!languageType.equals(this.languageType))
			{
				this.languageType = languageType;
				setChanged(true);
			}
		}
		else
		{
			if(languageType != this.languageType)
			{
				this.languageType = languageType;
				setChanged(true);
			}
		}
	}

	/**
	 * 公告
	 */
	public String getNoticeMessage()
	{
		return noticeMessage;
	}

	/**
	 * 公告
	 */
	public void setNoticeMessage(String noticeMessage)
	{
		if(noticeMessage != null)
		{
			if(!noticeMessage.equals(this.noticeMessage))
			{
				this.noticeMessage = noticeMessage;
				setChanged(true);
			}
		}
		else
		{
			if(noticeMessage != this.noticeMessage)
			{
				this.noticeMessage = noticeMessage;
				setChanged(true);
			}
		}
	}


	/**
	 * x.clone() != x
	 */
	public CommonData clone()
	{
		CommonData clone = new CommonData();
		clone.setNoticeType(this.getNoticeType());
		clone.setLanguageType(this.getLanguageType());
		clone.setNoticeMessage(this.getNoticeMessage());
		return clone;
	}

	/**
	 * 重置信息
	 */
	public void reset(CommonData info)
	{
		this.setNoticeType(info.getNoticeType());
		this.setLanguageType(info.getLanguageType());
		this.setNoticeMessage(info.getNoticeMessage());
	}

}