package com.data.account.data;

import com.base.data.ChangedObject;

/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class ServerData extends ChangedObject
{
    /**
     * 服务器ID
     */
    private int serverID;

    /**
     * 名称
     */
    private String serverName;

    /**
     * 地址
     */
    private String host;

    /**
     * Tcp端口
     */
    private int gamePort;

    /**
     * Web端口
     */
    private int webPort;

    /**
     * 注册人数
     */
    private int registerCount;

    /**
     * 服务器状态 1：开启；2：维护；3：测试；
     */
    private int state;

    public ServerData()
    {
        super();
    }

    /**
     * 服务器ID
     */
    public int getServerID()
    {
        return serverID;
    }

    /**
     * 服务器ID
     */
    public void setServerID(int serverID)
    {
        if (serverID != this.serverID)
        {
            this.serverID = serverID;
            setChanged(true);
        }
    }

    /**
     * 名称
     */
    public String getServerName()
    {
        return serverName;
    }

    /**
     * 名称
     */
    public void setServerName(String serverName)
    {
        if (serverName != null)
        {
            if (!serverName.equals(this.serverName))
            {
                this.serverName = serverName;
                setChanged(true);
            }
        }
        else
        {
            if (serverName != this.serverName)
            {
                this.serverName = serverName;
                setChanged(true);
            }
        }
    }

    /**
     * 地址
     */
    public String getHost()
    {
        return host;
    }

    /**
     * 地址
     */
    public void setHost(String host)
    {
        if (host != null)
        {
            if (!host.equals(this.host))
            {
                this.host = host;
                setChanged(true);
            }
        }
        else
        {
            if (host != this.host)
            {
                this.host = host;
                setChanged(true);
            }
        }
    }

    /**
     * Tcp端口
     */
    public int getGamePort()
    {
        return gamePort;
    }

    /**
     * Tcp端口
     */
    public void setGamePort(int gamePort)
    {
        if (gamePort != this.gamePort)
        {
            this.gamePort = gamePort;
            setChanged(true);
        }
    }

    /**
     * Web端口
     */
    public int getWebPort()
    {
        return webPort;
    }

    /**
     * Web端口
     */
    public void setWebPort(int webPort)
    {
        if (webPort != this.webPort)
        {
            this.webPort = webPort;
            setChanged(true);
        }
    }

    /**
     * 注册人数
     */
    public int getRegisterCount()
    {
        return registerCount;
    }

    /**
     * 注册人数
     */
    public void setRegisterCount(int registerCount)
    {
        if (registerCount != this.registerCount)
        {
            this.registerCount = registerCount;
            setChanged(true);
        }
    }

    /**
     * 服务器状态 1：开启；2：维护；3：测试；
     */
    public int getState()
    {
        return state;
    }

    /**
     * 服务器状态 1：开启；2：维护；3：测试；
     */
    public void setState(int state)
    {
        if (state != this.state)
        {
            this.state = state;
            setChanged(true);
        }
    }

    /**
     * x.clone() != x
     */
    public ServerData clone()
    {
        ServerData clone = new ServerData();
        clone.setServerID(this.getServerID());
        clone.setServerName(this.getServerName());
        clone.setHost(this.getHost());
        clone.setGamePort(this.getGamePort());
        clone.setWebPort(this.getWebPort());
        clone.setRegisterCount(this.getRegisterCount());
        clone.setState(this.getState());
        return clone;
    }

    /**
     * 重置信息
     */
    public void reset(ServerData info)
    {
        this.setServerID(info.getServerID());
        this.setServerName(info.getServerName());
        this.setHost(info.getHost());
        this.setGamePort(info.getGamePort());
        this.setWebPort(info.getWebPort());
        this.setRegisterCount(info.getRegisterCount());
        this.setState(info.getState());
    }

}
