package com.data.account.data;

import java.util.Date;

import com.base.data.ChangedObject;

/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class UserData extends ChangedObject 
{
	/**
	 * 玩家ID
	 */
	private long userID;

	/**
	 * OpenID
	 */
	private String openID;

	/**
	 * 玩家名
	 */
	private String userName;

	/**
	 * 注册日期
	 */
	private Date registerDate;

	/**
	 * 上次登录日期
	 */
	private Date lastLoginDate;

	/**
	 * 机器码信息
	 */
	private String machineCode;

	/**
	 * 绑定的GName
	 */
	private String gName;


    public UserData()
    {
       super();
    }

	/**
	 * 玩家ID
	 */
	public long getUserID()
	{
		return userID;
	}

	/**
	 * 玩家ID
	 */
	public void setUserID(long userID)
	{
		if(userID != this.userID)
		{
			this.userID = userID;
			setChanged(true);
		}
	}

	/**
	 * OpenID
	 */
	public String getOpenID()
	{
		return openID;
	}

	/**
	 * OpenID
	 */
	public void setOpenID(String openID)
	{
		if(openID != null)
		{
			if(!openID.equals(this.openID))
			{
				this.openID = openID;
				setChanged(true);
			}
		}
		else
		{
			if(openID != this.openID)
			{
				this.openID = openID;
				setChanged(true);
			}
		}
	}

	/**
	 * 玩家名
	 */
	public String getUserName()
	{
		return userName;
	}

	/**
	 * 玩家名
	 */
	public void setUserName(String userName)
	{
		if(userName != null)
		{
			if(!userName.equals(this.userName))
			{
				this.userName = userName;
				setChanged(true);
			}
		}
		else
		{
			if(userName != this.userName)
			{
				this.userName = userName;
				setChanged(true);
			}
		}
	}

	/**
	 * 注册日期
	 */
	public Date getRegisterDate()
	{
		return registerDate;
	}

	/**
	 * 注册日期
	 */
	public void setRegisterDate(Date registerDate)
	{
		if(registerDate != null)
		{
			if(!registerDate.equals(this.registerDate))
			{
				this.registerDate = registerDate;
				setChanged(true);
			}
		}
		else
		{
			if(registerDate != this.registerDate)
			{
				this.registerDate = registerDate;
				setChanged(true);
			}
		}
	}

	/**
	 * 上次登录日期
	 */
	public Date getLastLoginDate()
	{
		return lastLoginDate;
	}

	/**
	 * 上次登录日期
	 */
	public void setLastLoginDate(Date lastLoginDate)
	{
		if(lastLoginDate != null)
		{
			if(!lastLoginDate.equals(this.lastLoginDate))
			{
				this.lastLoginDate = lastLoginDate;
				setChanged(true);
			}
		}
		else
		{
			if(lastLoginDate != this.lastLoginDate)
			{
				this.lastLoginDate = lastLoginDate;
				setChanged(true);
			}
		}
	}

	/**
	 * 机器码信息
	 */
	public String getMachineCode()
	{
		return machineCode;
	}

	/**
	 * 机器码信息
	 */
	public void setMachineCode(String machineCode)
	{
		if(machineCode != null)
		{
			if(!machineCode.equals(this.machineCode))
			{
				this.machineCode = machineCode;
				setChanged(true);
			}
		}
		else
		{
			if(machineCode != this.machineCode)
			{
				this.machineCode = machineCode;
				setChanged(true);
			}
		}
	}

	/**
	 * 绑定的GName
	 */
	public String getGName()
	{
		return gName;
	}

	/**
	 * 绑定的GName
	 */
	public void setGName(String gName)
	{
		if(gName != null)
		{
			if(!gName.equals(this.gName))
			{
				this.gName = gName;
				setChanged(true);
			}
		}
		else
		{
			if(gName != this.gName)
			{
				this.gName = gName;
				setChanged(true);
			}
		}
	}


	/**
	 * x.clone() != x
	 */
	public UserData clone()
	{
		UserData clone = new UserData();
		clone.setUserID(this.getUserID());
		clone.setOpenID(this.getOpenID());
		clone.setUserName(this.getUserName());
		clone.setRegisterDate(this.getRegisterDate());
		clone.setLastLoginDate(this.getLastLoginDate());
		clone.setMachineCode(this.getMachineCode());
		clone.setGName(this.getGName());
		return clone;
	}

	/**
	 * 重置信息
	 */
	public void reset(UserData info)
	{
		this.setUserID(info.getUserID());
		this.setOpenID(info.getOpenID());
		this.setUserName(info.getUserName());
		this.setRegisterDate(info.getRegisterDate());
		this.setLastLoginDate(info.getLastLoginDate());
		this.setMachineCode(info.getMachineCode());
		this.setGName(info.getGName());
	}

}