package com.data.account.data;


import com.base.data.ChangedObject;

/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class VersionData extends ChangedObject 
{
	/**
	 * 版本
	 */
	private int versionID;

	/**
	 * 说明
	 */
	private String versionDesc;

	/**
	 * 是否强制更新
	 */
	private boolean isForce;


    public VersionData()
    {
       super();
    }

	/**
	 * 版本
	 */
	public int getVersionID()
	{
		return versionID;
	}

	/**
	 * 版本
	 */
	public void setVersionID(int versionID)
	{
		if(versionID != this.versionID)
		{
			this.versionID = versionID;
			setChanged(true);
		}
	}

	/**
	 * 说明
	 */
	public String getVersionDesc()
	{
		return versionDesc;
	}

	/**
	 * 说明
	 */
	public void setVersionDesc(String versionDesc)
	{
		if(versionDesc != null)
		{
			if(!versionDesc.equals(this.versionDesc))
			{
				this.versionDesc = versionDesc;
				setChanged(true);
			}
		}
		else
		{
			if(versionDesc != this.versionDesc)
			{
				this.versionDesc = versionDesc;
				setChanged(true);
			}
		}
	}

	/**
	 * 是否强制更新
	 */
	public boolean getIsForce()
	{
		return isForce;
	}

	/**
	 * 是否强制更新
	 */
	public void setIsForce(boolean isForce)
	{
		if(isForce != this.isForce)
		{
			this.isForce = isForce;
			setChanged(true);
		}
	}


	/**
	 * x.clone() != x
	 */
	public VersionData clone()
	{
		VersionData clone = new VersionData();
		clone.setVersionID(this.getVersionID());
		clone.setVersionDesc(this.getVersionDesc());
		clone.setIsForce(this.getIsForce());
		return clone;
	}

	/**
	 * 重置信息
	 */
	public void reset(VersionData info)
	{
		this.setVersionID(info.getVersionID());
		this.setVersionDesc(info.getVersionDesc());
		this.setIsForce(info.getIsForce());
	}

}