package com.data.factory;

import com.data.dao.IChargeInfoDao;
import com.data.dao.impl.ChargeInfoDaoImpl;


/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class ChargeInfoFactory implements IDaoFactory
{
    private static IChargeInfoDao dao;

    public static IChargeInfoDao getDao()
    {
		if (dao == null)
			dao = new ChargeInfoDaoImpl(mainHelper);

        return dao;
    }
}