package com.data.factory;

import com.data.dao.IPlayerInfoDao;
import com.data.dao.impl.PlayerInfoDaoImpl;


/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class PlayerInfoFactory implements IDaoFactory
{
    private static IPlayerInfoDao dao;

    public static IPlayerInfoDao getDao()
    {
		if (dao == null)
			dao = new PlayerInfoDaoImpl(mainHelper);

        return dao;
    }
}