package com.data.factory;

import com.data.dao.IRankInfoDao;
import com.data.dao.impl.RankInfoDaoImpl;


/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class RankInfoFactory implements IDaoFactory
{
    private static IRankInfoDao dao;

    public static IRankInfoDao getDao()
    {
		if (dao == null)
			dao = new RankInfoDaoImpl(mainHelper);

        return dao;
    }
}