package com.data.info;

import java.util.Date;

import com.base.data.ChangedObject;

/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class ChargeInfo extends ChangedObject 
{
	/**
	 * 玩家ID
	 */
	private long userID;

	/**
	 * 订单编号
	 */
	private String orderId;

	/**
	 * 账号
	 */
	private String accountName;

	/**
	 * 支付方式(微信、支付宝.......)
	 */
	private String payWay;

	/**
	 * 支付货币数额
	 */
	private float payMoney;

	/**
	 * 支付时间
	 */
	private Date payTime;

	/**
	 * 充值ID
	 */
	private int configID;

	/**
	 * 游戏订单时间
	 */
	private Date createTime;

	/**
	 * 订单状态
	 */
	private int orderStatus;

	/**
	 * Token
	 */
	private String purchaseToken;


    public ChargeInfo()
    {
       super();
    }

	/**
	 * 玩家ID
	 */
	public long getUserID()
	{
		return userID;
	}

	/**
	 * 玩家ID
	 */
	public void setUserID(long userID)
	{
		if(userID != this.userID)
		{
			this.userID = userID;
			setChanged(true);
		}
	}

	/**
	 * 订单编号
	 */
	public String getOrderId()
	{
		return orderId;
	}

	/**
	 * 订单编号
	 */
	public void setOrderId(String orderId)
	{
		if(orderId != null)
		{
			if(!orderId.equals(this.orderId))
			{
				this.orderId = orderId;
				setChanged(true);
			}
		}
		else
		{
			if(orderId != this.orderId)
			{
				this.orderId = orderId;
				setChanged(true);
			}
		}
	}

	/**
	 * 账号
	 */
	public String getAccountName()
	{
		return accountName;
	}

	/**
	 * 账号
	 */
	public void setAccountName(String accountName)
	{
		if(accountName != null)
		{
			if(!accountName.equals(this.accountName))
			{
				this.accountName = accountName;
				setChanged(true);
			}
		}
		else
		{
			if(accountName != this.accountName)
			{
				this.accountName = accountName;
				setChanged(true);
			}
		}
	}

	/**
	 * 支付方式(微信、支付宝.......)
	 */
	public String getPayWay()
	{
		return payWay;
	}

	/**
	 * 支付方式(微信、支付宝.......)
	 */
	public void setPayWay(String payWay)
	{
		if(payWay != null)
		{
			if(!payWay.equals(this.payWay))
			{
				this.payWay = payWay;
				setChanged(true);
			}
		}
		else
		{
			if(payWay != this.payWay)
			{
				this.payWay = payWay;
				setChanged(true);
			}
		}
	}

	/**
	 * 支付货币数额
	 */
	public float getPayMoney()
	{
		return payMoney;
	}

	/**
	 * 支付货币数额
	 */
	public void setPayMoney(float payMoney)
	{
		if(payMoney != this.payMoney)
		{
			this.payMoney = payMoney;
			setChanged(true);
		}
	}

	/**
	 * 支付时间
	 */
	public Date getPayTime()
	{
		return payTime;
	}

	/**
	 * 支付时间
	 */
	public void setPayTime(Date payTime)
	{
		if(payTime != null)
		{
			if(!payTime.equals(this.payTime))
			{
				this.payTime = payTime;
				setChanged(true);
			}
		}
		else
		{
			if(payTime != this.payTime)
			{
				this.payTime = payTime;
				setChanged(true);
			}
		}
	}

	/**
	 * 充值ID
	 */
	public int getConfigID()
	{
		return configID;
	}

	/**
	 * 充值ID
	 */
	public void setConfigID(int configID)
	{
		if(configID != this.configID)
		{
			this.configID = configID;
			setChanged(true);
		}
	}

	/**
	 * 游戏订单时间
	 */
	public Date getCreateTime()
	{
		return createTime;
	}

	/**
	 * 游戏订单时间
	 */
	public void setCreateTime(Date createTime)
	{
		if(createTime != null)
		{
			if(!createTime.equals(this.createTime))
			{
				this.createTime = createTime;
				setChanged(true);
			}
		}
		else
		{
			if(createTime != this.createTime)
			{
				this.createTime = createTime;
				setChanged(true);
			}
		}
	}

	/**
	 * 订单状态
	 */
	public int getOrderStatus()
	{
		return orderStatus;
	}

	/**
	 * 订单状态
	 */
	public void setOrderStatus(int orderStatus)
	{
		if(orderStatus != this.orderStatus)
		{
			this.orderStatus = orderStatus;
			setChanged(true);
		}
	}

	/**
	 * Token
	 */
	public String getPurchaseToken()
	{
		return purchaseToken;
	}

	/**
	 * Token
	 */
	public void setPurchaseToken(String purchaseToken)
	{
		if(purchaseToken != null)
		{
			if(!purchaseToken.equals(this.purchaseToken))
			{
				this.purchaseToken = purchaseToken;
				setChanged(true);
			}
		}
		else
		{
			if(purchaseToken != this.purchaseToken)
			{
				this.purchaseToken = purchaseToken;
				setChanged(true);
			}
		}
	}


	/**
	 * x.clone() != x
	 */
	public ChargeInfo clone()
	{
		ChargeInfo clone = new ChargeInfo();
		clone.setUserID(this.getUserID());
		clone.setOrderId(this.getOrderId());
		clone.setAccountName(this.getAccountName());
		clone.setPayWay(this.getPayWay());
		clone.setPayMoney(this.getPayMoney());
		clone.setPayTime(this.getPayTime());
		clone.setConfigID(this.getConfigID());
		clone.setCreateTime(this.getCreateTime());
		clone.setOrderStatus(this.getOrderStatus());
		clone.setPurchaseToken(this.getPurchaseToken());
		return clone;
	}

	/**
	 * 重置信息
	 */
	public void reset(ChargeInfo info)
	{
		this.setUserID(info.getUserID());
		this.setOrderId(info.getOrderId());
		this.setAccountName(info.getAccountName());
		this.setPayWay(info.getPayWay());
		this.setPayMoney(info.getPayMoney());
		this.setPayTime(info.getPayTime());
		this.setConfigID(info.getConfigID());
		this.setCreateTime(info.getCreateTime());
		this.setOrderStatus(info.getOrderStatus());
		this.setPurchaseToken(info.getPurchaseToken());
	}

}