package com.data.info;

import java.util.Date;

import com.base.data.ChangedObject;

/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class LineRankInfo extends ChangedObject 
{
	/**
	 * 玩家ID
	 */
	private int userID;

	/**
	 * 当前所在层数
	 */
	private long level;

	/**
	 * 剩余次数
	 */
	private int leftCount;

	/**
	 * 上次时间
	 */
	private Date lastAdTime;


    public LineRankInfo()
    {
       super();
    }

	/**
	 * 玩家ID
	 */
	public int getUserID()
	{
		return userID;
	}

	/**
	 * 玩家ID
	 */
	public void setUserID(int userID)
	{
		if(userID != this.userID)
		{
			this.userID = userID;
			setChanged(true);
		}
	}

	/**
	 * 当前所在层数
	 */
	public long getLevel()
	{
		return level;
	}

	/**
	 * 当前所在层数
	 */
	public void setLevel(long level)
	{
		if(level != this.level)
		{
			this.level = level;
			setChanged(true);
		}
	}

	/**
	 * 剩余次数
	 */
	public int getLeftCount()
	{
		return leftCount;
	}

	/**
	 * 剩余次数
	 */
	public void setLeftCount(int leftCount)
	{
		if(leftCount != this.leftCount)
		{
			this.leftCount = leftCount;
			setChanged(true);
		}
	}

	/**
	 * 上次时间
	 */
	public Date getLastAdTime()
	{
		return lastAdTime;
	}

	/**
	 * 上次时间
	 */
	public void setLastAdTime(Date lastAdTime)
	{
		if(lastAdTime != null)
		{
			if(!lastAdTime.equals(this.lastAdTime))
			{
				this.lastAdTime = lastAdTime;
				setChanged(true);
			}
		}
		else
		{
			if(lastAdTime != this.lastAdTime)
			{
				this.lastAdTime = lastAdTime;
				setChanged(true);
			}
		}
	}


	/**
	 * x.clone() != x
	 */
	public LineRankInfo clone()
	{
		LineRankInfo clone = new LineRankInfo();
		clone.setUserID(this.getUserID());
		clone.setLevel(this.getLevel());
		clone.setLeftCount(this.getLeftCount());
		clone.setLastAdTime(this.getLastAdTime());
		return clone;
	}

	/**
	 * 重置信息
	 */
	public void reset(LineRankInfo info)
	{
		this.setUserID(info.getUserID());
		this.setLevel(info.getLevel());
		this.setLeftCount(info.getLeftCount());
		this.setLastAdTime(info.getLastAdTime());
	}

}