package com.data.info;

import java.util.Date;

import com.base.data.ChangedObject;

/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class RankInfo extends ChangedObject 
{
	/**
	 * 排行类型
	 */
	private int rankType;

	/**
	 * 排行时间类型
	 */
	private int timeType;

	/**
	 * 玩家ID
	 */
	private int userID;

	/**
	 * 排名值
	 */
	private int rankValue;

	/**
	 * 更新时间
	 */
	private Date updateTime;

	/**
	 * 头像
	 */
	private int header;

	/**
	 * 昵称
	 */
	private String nickName;

	/**
	 * 排行
	 */
	private int order;


    public RankInfo()
    {
       super();
    }

	/**
	 * 排行类型
	 */
	public int getRankType()
	{
		return rankType;
	}

	/**
	 * 排行类型
	 */
	public void setRankType(int rankType)
	{
		if(rankType != this.rankType)
		{
			this.rankType = rankType;
			setChanged(true);
		}
	}

	/**
	 * 排行时间类型
	 */
	public int getTimeType()
	{
		return timeType;
	}

	/**
	 * 排行时间类型
	 */
	public void setTimeType(int timeType)
	{
		if(timeType != this.timeType)
		{
			this.timeType = timeType;
			setChanged(true);
		}
	}

	/**
	 * 玩家ID
	 */
	public int getUserID()
	{
		return userID;
	}

	/**
	 * 玩家ID
	 */
	public void setUserID(int userID)
	{
		if(userID != this.userID)
		{
			this.userID = userID;
			setChanged(true);
		}
	}

	/**
	 * 排名值
	 */
	public int getRankValue()
	{
		return rankValue;
	}

	/**
	 * 排名值
	 */
	public void setRankValue(int rankValue)
	{
		if(rankValue != this.rankValue)
		{
			this.rankValue = rankValue;
			setChanged(true);
		}
	}

	/**
	 * 更新时间
	 */
	public Date getUpdateTime()
	{
		return updateTime;
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(Date updateTime)
	{
		if(updateTime != null)
		{
			if(!updateTime.equals(this.updateTime))
			{
				this.updateTime = updateTime;
				setChanged(true);
			}
		}
		else
		{
			if(updateTime != this.updateTime)
			{
				this.updateTime = updateTime;
				setChanged(true);
			}
		}
	}

	/**
	 * 头像
	 */
	public int getHeader()
	{
		return header;
	}

	/**
	 * 头像
	 */
	public void setHeader(int header)
	{
		if(header != this.header)
		{
			this.header = header;
			setChanged(true);
		}
	}

	/**
	 * 昵称
	 */
	public String getNickName()
	{
		return nickName;
	}

	/**
	 * 昵称
	 */
	public void setNickName(String nickName)
	{
		if(nickName != null)
		{
			if(!nickName.equals(this.nickName))
			{
				this.nickName = nickName;
				setChanged(true);
			}
		}
		else
		{
			if(nickName != this.nickName)
			{
				this.nickName = nickName;
				setChanged(true);
			}
		}
	}

	/**
	 * 排行
	 */
	public int getOrder()
	{
		return order;
	}

	/**
	 * 排行
	 */
	public void setOrder(int order)
	{
		if(order != this.order)
		{
			this.order = order;
			setChanged(true);
		}
	}


	/**
	 * x.clone() != x
	 */
	public RankInfo clone()
	{
		RankInfo clone = new RankInfo();
		clone.setRankType(this.getRankType());
		clone.setTimeType(this.getTimeType());
		clone.setUserID(this.getUserID());
		clone.setRankValue(this.getRankValue());
		clone.setUpdateTime(this.getUpdateTime());
		clone.setHeader(this.getHeader());
		clone.setNickName(this.getNickName());
		clone.setOrder(this.getOrder());
		return clone;
	}

	/**
	 * 重置信息
	 */
	public void reset(RankInfo info)
	{
		this.setRankType(info.getRankType());
		this.setTimeType(info.getTimeType());
		this.setUserID(info.getUserID());
		this.setRankValue(info.getRankValue());
		this.setUpdateTime(info.getUpdateTime());
		this.setHeader(info.getHeader());
		this.setNickName(info.getNickName());
		this.setOrder(info.getOrder());
	}

}