package com.data.account.factory;

import com.data.account.dao.ICommonDataDao;
import com.data.account.dao.impl.CommonDataDaoImpl;


/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class CommonDataFactory implements IDaoFactory
{
    private static ICommonDataDao dao;

    public static ICommonDataDao getDao()
    {
		if (dao == null)
			dao = new CommonDataDaoImpl(mainHelper);

        return dao;
    }
}