package com.data.account.factory;

import com.data.account.dao.IServerDataDao;
import com.data.account.dao.impl.ServerDataDaoImpl;


/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class ServerDataFactory implements IDaoFactory
{
    private static IServerDataDao dao;

    public static IServerDataDao getDao()
    {
		if (dao == null)
			dao = new ServerDataDaoImpl(mainHelper);

        return dao;
    }
}