package com.data.account.factory;

import com.data.account.dao.IUserDataDao;
import com.data.account.dao.impl.UserDataDaoImpl;


/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class UserDataFactory implements IDaoFactory
{
    private static IUserDataDao dao;

    public static IUserDataDao getDao()
    {
		if (dao == null)
			dao = new UserDataDaoImpl(mainHelper);

        return dao;
    }
}