package com.data.account.factory;

import com.data.account.dao.IVersionDataDao;
import com.data.account.dao.impl.VersionDataDaoImpl;


/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class VersionDataFactory implements IDaoFactory
{
    private static IVersionDataDao dao;

    public static IVersionDataDao getDao()
    {
		if (dao == null)
			dao = new VersionDataDaoImpl(mainHelper);

        return dao;
    }
}