package com.data.dao;

import com.base.database.IBaseDao;
import java.util.List;

import com.data.info.LineRankInfo;


/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public interface ILineRankInfoDao extends IBaseDao<LineRankInfo>
{
	LineRankInfo getLineRankInfoByUserID(int userID);

}
