package com.data.dao;

import com.base.database.IBaseDao;
import java.util.List;

import com.data.info.PlayerInfo;


/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public interface IPlayerInfoDao extends IBaseDao<PlayerInfo>
{
	PlayerInfo getPlayerInfoByUserID(int userID);

}
