package com.data.dao;

import com.base.database.IBaseDao;
import java.util.List;

import com.data.info.RankInfo;


/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public interface IRankInfoDao extends IBaseDao<RankInfo>
{
	List<RankInfo> getRankInfoByUserID(int userID);

}
