package com.data.account.dao;

import com.base.database.IBaseDao;
import java.util.List;

import com.data.account.info.DataInfo;


/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public interface IDataInfoDao extends IBaseDao<DataInfo>
{
	List<DataInfo> getDataInfoByUserID(long userID);

}
