package com.data.log;

import java.util.Date;

import com.base.data.ChangedObject;

/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class LoginLog extends ChangedObject 
{
	/**
	 * 主键
	 */
	private int keyID;

	/**
	 * 用户ID
	 */
	private int userID;

	/**
	 * 登录类型：0-登录，1-登出
	 */
	private short logType;

	/**
	 * 记录时间
	 */
	private Date logTime;

	/**
	 * 用户等级
	 */
	private int userLevel;

	/**
	 * 在线时长（秒，只有登出才有效）
	 */
	private int onlineTime;

	/**
	 * 登录角色机器码
	 */
	private String machineID;

	/**
	 * 登录角色IP
	 */
	private String loginIP;

	/**
	 * 服务器ID
	 */
	private int serverID;


    public LoginLog()
    {
       super();
    }

	/**
	 * 主键
	 */
	public int getKeyID()
	{
		return keyID;
	}

	/**
	 * 主键
	 */
	public void setKeyID(int keyID)
	{
		if(keyID != this.keyID)
		{
			this.keyID = keyID;
			setChanged(true);
		}
	}

	/**
	 * 用户ID
	 */
	public int getUserID()
	{
		return userID;
	}

	/**
	 * 用户ID
	 */
	public void setUserID(int userID)
	{
		if(userID != this.userID)
		{
			this.userID = userID;
			setChanged(true);
		}
	}

	/**
	 * 登录类型：0-登录，1-登出
	 */
	public short getLogType()
	{
		return logType;
	}

	/**
	 * 登录类型：0-登录，1-登出
	 */
	public void setLogType(short logType)
	{
		if(logType != this.logType)
		{
			this.logType = logType;
			setChanged(true);
		}
	}

	/**
	 * 记录时间
	 */
	public Date getLogTime()
	{
		return logTime;
	}

	/**
	 * 记录时间
	 */
	public void setLogTime(Date logTime)
	{
		if(logTime != null)
		{
			if(!logTime.equals(this.logTime))
			{
				this.logTime = logTime;
				setChanged(true);
			}
		}
		else
		{
			if(logTime != this.logTime)
			{
				this.logTime = logTime;
				setChanged(true);
			}
		}
	}

	/**
	 * 用户等级
	 */
	public int getUserLevel()
	{
		return userLevel;
	}

	/**
	 * 用户等级
	 */
	public void setUserLevel(int userLevel)
	{
		if(userLevel != this.userLevel)
		{
			this.userLevel = userLevel;
			setChanged(true);
		}
	}

	/**
	 * 在线时长（秒，只有登出才有效）
	 */
	public int getOnlineTime()
	{
		return onlineTime;
	}

	/**
	 * 在线时长（秒，只有登出才有效）
	 */
	public void setOnlineTime(int onlineTime)
	{
		if(onlineTime != this.onlineTime)
		{
			this.onlineTime = onlineTime;
			setChanged(true);
		}
	}

	/**
	 * 登录角色机器码
	 */
	public String getMachineID()
	{
		return machineID;
	}

	/**
	 * 登录角色机器码
	 */
	public void setMachineID(String machineID)
	{
		if(machineID != null)
		{
			if(!machineID.equals(this.machineID))
			{
				this.machineID = machineID;
				setChanged(true);
			}
		}
		else
		{
			if(machineID != this.machineID)
			{
				this.machineID = machineID;
				setChanged(true);
			}
		}
	}

	/**
	 * 登录角色IP
	 */
	public String getLoginIP()
	{
		return loginIP;
	}

	/**
	 * 登录角色IP
	 */
	public void setLoginIP(String loginIP)
	{
		if(loginIP != null)
		{
			if(!loginIP.equals(this.loginIP))
			{
				this.loginIP = loginIP;
				setChanged(true);
			}
		}
		else
		{
			if(loginIP != this.loginIP)
			{
				this.loginIP = loginIP;
				setChanged(true);
			}
		}
	}

	/**
	 * 服务器ID
	 */
	public int getServerID()
	{
		return serverID;
	}

	/**
	 * 服务器ID
	 */
	public void setServerID(int serverID)
	{
		if(serverID != this.serverID)
		{
			this.serverID = serverID;
			setChanged(true);
		}
	}


	/**
	 * x.clone() != x
	 */
	public LoginLog clone()
	{
		LoginLog clone = new LoginLog();
		clone.setKeyID(this.getKeyID());
		clone.setUserID(this.getUserID());
		clone.setLogType(this.getLogType());
		clone.setLogTime(this.getLogTime());
		clone.setUserLevel(this.getUserLevel());
		clone.setOnlineTime(this.getOnlineTime());
		clone.setMachineID(this.getMachineID());
		clone.setLoginIP(this.getLoginIP());
		clone.setServerID(this.getServerID());
		return clone;
	}

	/**
	 * 重置信息
	 */
	public void reset(LoginLog info)
	{
		this.setKeyID(info.getKeyID());
		this.setUserID(info.getUserID());
		this.setLogType(info.getLogType());
		this.setLogTime(info.getLogTime());
		this.setUserLevel(info.getUserLevel());
		this.setOnlineTime(info.getOnlineTime());
		this.setMachineID(info.getMachineID());
		this.setLoginIP(info.getLoginIP());
		this.setServerID(info.getServerID());
	}

}