package com.data.log;

import java.util.Date;

import com.base.data.ChangedObject;

/**
 * This file is generated by system automatically.Don't Modify It.
 *
 * @author System
 */
public final class ResourceLog extends ChangedObject
{
    private int keyID;

    private int userID;

    private int itemID;

    private int itemCount;

    private int addType;

    private Date addTime;

    public ResourceLog()
    {
        super();
    }

    /**
     * 
     */
    public int getKeyID()
    {
        return keyID;
    }

    /**
     * 
     */
    public void setKeyID(int keyID)
    {
        if (keyID != this.keyID)
        {
            this.keyID = keyID;
            setChanged(true);
        }
    }

    /**
     * 
     */
    public int getUserID()
    {
        return userID;
    }

    /**
     * 
     */
    public void setUserID(int userID)
    {
        if (userID != this.userID)
        {
            this.userID = userID;
            setChanged(true);
        }
    }

    /**
     * 
     */
    public int getItemID()
    {
        return itemID;
    }

    /**
     * 
     */
    public void setItemID(int itemID)
    {
        if (itemID != this.itemID)
        {
            this.itemID = itemID;
            setChanged(true);
        }
    }

    /**
     * 
     */
    public int getItemCount()
    {
        return itemCount;
    }

    /**
     * 
     */
    public void setItemCount(int itemCount)
    {
        if (itemCount != this.itemCount)
        {
            this.itemCount = itemCount;
            setChanged(true);
        }
    }

    /**
     * 
     */
    public int getAddType()
    {
        return addType;
    }

    /**
     * 
     */
    public void setAddType(int addType)
    {
        if (addType != this.addType)
        {
            this.addType = addType;
            setChanged(true);
        }
    }

    /**
     * 
     */
    public Date getAddTime()
    {
        return addTime;
    }

    /**
     * 
     */
    public void setAddTime(Date addTime)
    {
        if (addTime != null)
        {
            if (!addTime.equals(this.addTime))
            {
                this.addTime = addTime;
                setChanged(true);
            }
        }
        else
        {
            if (addTime != this.addTime)
            {
                this.addTime = addTime;
                setChanged(true);
            }
        }
    }

    /**
     * x.clone() != x
     */
    public ResourceLog clone()
    {
        ResourceLog clone = new ResourceLog();
        clone.setKeyID(this.getKeyID());
        clone.setUserID(this.getUserID());
        clone.setItemID(this.getItemID());
        clone.setItemCount(this.getItemCount());
        clone.setAddType(this.getAddType());
        clone.setAddTime(this.getAddTime());
        return clone;
    }

    /**
     * 重置信息
     */
    public void reset(ResourceLog info)
    {
        this.setKeyID(info.getKeyID());
        this.setUserID(info.getUserID());
        this.setItemID(info.getItemID());
        this.setItemCount(info.getItemCount());
        this.setAddType(info.getAddType());
        this.setAddTime(info.getAddTime());
    }

}
